common: &common
  adapter: postgresql
  host: localhost
  min_messages: warning

development:
  <<: *common
  database: votecount_development

test: &test
  <<: *common
  database: votecount_test

production:
  <<: *common
  database: votecount_production

cucumber:
  <<: *test
